function B_mtrx = B_mtrx(in1,in2,u1,in4,me1,le1,me2,le2)
%B_MTRX
%    B_MTRX = B_MTRX(IN1,IN2,U1,IN4,ME1,LE1,ME2,LE2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    21-Feb-2021 16:45:44

p1 = in4(1,:);
p2 = in4(2,:);
p3 = in4(3,:);
q2 = in1(2,:);
t2 = cos(q2);
t3 = me2.*p3;
t4 = le1.^2;
t5 = le2.^2;
t6 = me2.^2;
t7 = p2.^2;
t8 = p3.^2;
t10 = p1.*p3.*1.6e+1;
t9 = t2.^2;
t11 = t8.*1.6e+1;
t13 = t5.*t6;
t14 = me1.*p3.*t4.*1.6e+1;
t15 = me2.*p1.*t5.*1.6e+1;
t16 = t3.*t5.*1.6e+1;
t22 = me1.*me2.*t4.*t5.*1.6e+1;
t12 = -t11;
t17 = -t16;
t18 = t7.*t9.*1.6e+1;
t19 = le2.*me2.*p2.*t9.*8.0;
t20 = t9.*t13;
t21 = -t18;
t23 = -t19;
t24 = -t20;
t25 = t3+t10+t12+t13+t14+t15+t17+t21+t22+t23+t24;
t26 = 1.0./t25;
B_mtrx = [0.0;0.0;(t26.*(p3.*2.26e+2+me2.*t5.*2.26e+2))./1.25e+2;t26.*(p3.*9.04e+2+me2.*t5.*9.04e+2+p2.*t2.*9.04e+2+le2.*me2.*t2.*2.26e+2).*(-1.0./5.0e+2)];
